name: Build and Distribute Debug IPA (iOS)

on:
  push:
    branches: [ "develop", "staging" ]
  workflow_dispatch:         # 手動実行も可能
    inputs:
      tester_group:
        description: 'Firebase tester group'
        required: false
        default: 'Clapp'
        type: choice
        options:
          - 'Clapp'
      release_notes:
        description: 'Release notes'
        required: false
        default: '動作確認用'

env:
  XCODE_VERSION: '26.0.1'           # 使用するXcodeのバージョン
  SCHEME: 'GithubActionsTest'        # Xcodeのビルド対象Scheme
  CONFIGURATION: 'Debug'          # Debugビルドを指定
  EXPORT_METHOD: 'development'    # ipa出力方法(development / ad-hoc / app-storeなど)

jobs:
  distribute:
    runs-on: macos-latest             # macOSランナー(Xcodeが使える環境)
    timeout-minutes: 45
    # environment: iOSDebug

    steps:
    # ---------------------------------------------
    # ① ソースコードをチェックアウト
    # ---------------------------------------------
    - name: Checkout code
      uses: actions/checkout@v4

    # ---------------------------------------------
    # ② Xcodeバージョンを指定
    # ---------------------------------------------
    - name: Set up Xcode
      run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

    # ---------------------------------------------
    # ③ ライブラリをインストール
    # ---------------------------------------------
    - name: Resolve Swift Packages
      run: xcodebuild -resolvePackageDependencies -project ${{ env.SCHEME }}.xcodeproj -scheme ${{ env.SCHEME }} -configuration Debug

    # ---------------------------------------------
    # ④ ビルド
    # ---------------------------------------------
    - name: Build app
      run: xcodebuild -project ${{ env.SCHEME }}.xcodeproj -scheme ${{ env.SCHEME }} -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=26.0'
