name: Build and Distribute Debug IPA (iOS)

on:
  push:
    branches: ["staging" ]
  pull_request:
    branches: [ "develop", "staging" ]
  workflow_dispatch:         # 手動実行も可能
    inputs:
      tester_group:
        description: 'Firebase tester group'
        required: false
        default: 'Clapp'
        type: choice
        options:
          - 'Clapp'
      release_notes:
        description: 'Release notes'
        required: false
        default: '動作確認用'

env:
  XCODE_VERSION: '26.0.1'           # 使用するXcodeのバージョン
  SIMULATOR_NAME: 'iPhone 17'       # 使用するiPhoneシミュレーターの種類
  SCHEME: 'GithubActionsApp'        # Xcodeのビルド対象Scheme
  CONFIGURATION: 'Debug'          # Debugビルドを指定
  EXPORT_METHOD: 'development'    # ipa出力方法(development / ad-hoc / app-storeなど)

jobs:
  distribute:
    runs-on: macos-latest             # macOSランナー(Xcodeが使える環境)
    timeout-minutes: 45
    # environment: iOSDebug

    steps:
    # ---------------------------------------------
    # ① ソースコードをチェックアウト
    # ---------------------------------------------
    - name: Checkout code
      uses: actions/checkout@v4

    # ---------------------------------------------
    # キャッシュ
    # ---------------------------------------------
    - name: Cache Swift Packages
      uses: actions/cache@v4
      with:
        path: |
          ~/Library/Developer/Xcode/DerivedData
          ~/Library/Caches/org.swift.swiftpm
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-

    # ---------------------------------------------
    # ② Xcodeバージョンを指定
    # ---------------------------------------------
    - name: Set up Xcode
      run: sudo xcode-select -s /Applications/Xcode_${{ env.XCODE_VERSION }}.app/Contents/Developer

    # ---------------------------------------------
    # ③ ライブラリをインストール
    # ---------------------------------------------
    - name: Resolve Swift Packages
      run: xcodebuild -resolvePackageDependencies -project ${{ env.SCHEME }}.xcodeproj -scheme ${{ env.SCHEME }} -configuration Debug

    # ---------------------------------------------
    # ④ ビルド
    # ---------------------------------------------
    - name: Build app
      run: xcodebuild -project ${{ env.SCHEME }}.xcodeproj -scheme ${{ env.SCHEME }} -configuration Debug -sdk iphonesimulator -destination "platform=iOS Simulator,name=${{ env.SIMULATOR_NAME }}"