name: Build and Distribute Debug IPA (iOS)

on:
  push:
    branches: [ "staging" ]  # stagingブランチへのpush時に実行
  workflow_dispatch:         # 手動実行も可能
    inputs:
      tester_group:
        description: 'Firebase tester group'
        required: false
        default: 'Clapp'
        type: choice
        options:
          - 'Clapp'
      release_notes:
        description: 'Release notes'
        required: false
        default: '動作確認用'

env:
  XCODE_VERSION: '26.0.1'           # 使用するXcodeのバージョン
  SCHEME: 'GithubActionTest'                 # Xcodeのビルド対象Scheme
  WORKSPACE: 'GithubActionTest.xcworkspace'  # CocoaPods使用時のworkspace名
  CONFIGURATION: 'Debug'          # Debugビルドを指定
  EXPORT_METHOD: 'development'    # ipa出力方法(development / ad-hoc / app-storeなど)

jobs:
  distribute:
    runs-on: macos-latest             # macOSランナー(Xcodeが使える環境)
    timeout-minutes: 45
    # environment: iOSDebug

    steps:
    # ---------------------------------------------
    # ① ソースコードをチェックアウト
    # ---------------------------------------------
    - name: Checkout code
      uses: actions/checkout@v4

    # ---------------------------------------------
    # ② Xcodeバージョンを指定
    # ---------------------------------------------
    - name: Set up Xcode
      run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

    # ---------------------------------------------
    # ③ CocoaPods の依存ライブラリをインストール
    # ---------------------------------------------
    - name: Install dependencies (CocoaPods)
      run: |
        gem install cocoapods --no-document
        pod repo update
        pod install
